name: api_petvida03
description: "App PetVida â€” Sistema de Agendamento e NotificaÃ§Ãµes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ğŸ“¦ DependÃªncias principais
  http: ^1.2.2
  dio: ^5.7.0
  logger: ^2.6.2
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

  # ğŸ”¥ Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ğŸ–¼ï¸ Ative caso use imagens, Ã­cones ou PDF em assets
  assets:
    - assets/
    - assets/images/logo_petvida.jpg
    - assets/icons/
